import Head from 'next/head';

import Slider from "react-slick";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";

export default function Tiktok() {
  const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  const settings = {
    dots: false,
    infinite: false,
    slidesToShow: 3,
    slidesToScroll: 1,
    vertical: true,
    arrows: false,
    verticalSwiping: true,
    swipeToSlide: true,
    beforeChange: function (currentSlide, nextSlide) {
      console.log("before change", currentSlide, nextSlide);
    },
    afterChange: function (currentSlide) {
      console.log("after change", currentSlide);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='max-w-md mx-auto overflow-auto scrollbar-hide relative bg-white min-h-screen'>
        <Slider
          className="carousel-vertical max-h-screen"
          centerMode={false}
          infinite={false}
          slidesToScroll={1}
          speed={500}
          arrows={false}
          vertical={true}
          verticalSwiping={true}
          afterChange={(currentSlide) => {
            console.log("after change", currentSlide);
          }}
        >
          {
            data.map((item, index) =>
              <div
                key={index}
                className={`min-h-screen ${item % 2 == 0 ? 'bg-green-400' : 'bg-red-400'}`}
              >
                <h3>{item}</h3>
              </div>
            )
          }
        </Slider>
      </main>
    </>
  )
}
